apiVersion: v1
kind: Namespace
metadata:
  name: frontend-app-dev
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}
status: {}